/* ------------------------------------------------------------------
 * Generated by PYTHIA 0.1 from p1.py
 * Do not edit: regenerate with `python -m pythia.cli <source>.py`.
 * ---------------------------------------------------------------- */
#include "pyrt.h"

int main(void) {
    int64_t p_x = 0;
    int64_t p_y = 0;

    p_x = INT64_C(10);
    p_y = INT64_C(20);
    py_print_begin();
    py_print_sep();
    py_print_i64(((p_x) + (p_y)));
    py_print_end();
    return 0;
}
