"""
PYTHIA :: Phase 5 -- Target Code Generation (PIR -> C11)
Owner: Member 4 (Aaryan Gupta)

Emits readable C++17 using the C++ runtime and lambda IIFEs for expression
scopes that need to evaluate an operand exactly once.
"""
from typing import List, Optional
from . import ast_nodes as A
from .typecheck import Ty, INT, FLOAT, BOOL, STR, NONE, ERR, TypeChecker

LIST_RT = {"int": "PyListI64", "float": "PyListF64",
           "bool": "PyListBool", "str": "PyListStr"}

DICT_RT = {
    ("int", "int"): "PyDictIntInt", ("int", "float"): "PyDictIntFloat",
    ("int", "bool"): "PyDictIntBool", ("int", "str"): "PyDictIntStr",
    ("str", "int"): "PyDictStrInt", ("str", "float"): "PyDictStrFloat",
    ("str", "bool"): "PyDictStrBool", ("str", "str"): "PyDictStrStr",
}


def list_rt_name(t: Ty) -> str:
    """Runtime list type for list[elem]. Primitive elements are monomorphic
    (PyListI64 etc); anything else (nested list, class instance) is a
    pointer, so it rides the generic PyListList and gets cast at each use."""
    if t.elem is not None and t.elem.name in LIST_RT:
        return LIST_RT[t.elem.name]
    return "PyListList"


def dict_rt_name(t: Ty) -> str:
    return DICT_RT[(t.key.name, t.elem.name)]


def ctype(t: Optional[Ty]) -> str:
    if t is None or t is ERR:
        return "void"
    if t.name == "int":
        return "int64_t "
    if t.name == "float":
        return "double "
    if t.name == "bool":
        return "bool "
    if t.name == "str":
        return "PyStr *"
    if t.name == "None":
        return "void "
    if t.name == "list":
        return list_rt_name(t) + " *"
    if t.name == "dict":
        return dict_rt_name(t) + " *"
    return f"std::shared_ptr<{t.name}>"  # class instances use RAII ownership


def zero(t: Ty) -> str:
    return {"int": "0", "float": "0.0", "bool": "false"}.get(t.name, "NULL")


def c_string(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.extend(f"\\{b:03o}" for b in ch.encode("utf-8"))
    return '"' + "".join(out) + '"'


class Emitter:
    def __init__(self, tc: TypeChecker):
        self.tc = tc
        self.buf: List[str] = []
        self.tmp = 0
        self.wrappers: dict = {}      # str(elem_ty) -> (name, C source)

    def w(self, indent: int, line: str = "") -> None:
        self.buf.append("    " * indent + line if line else "")

    def fresh(self) -> str:
        self.tmp += 1
        return f"_t{self.tmp}"

    # ---- module ------------------------------------------------------------
    def emit_module(self, mod: A.Module, src_name: str) -> str:
        self.w(0, "/* ------------------------------------------------------------------")
        self.w(0, f" * Generated by PYTHIA 0.1 from {src_name}")
        self.w(0, " * Do not edit: regenerate with `python -m pythia.cli <source>.py`.")
        self.w(0, " * ---------------------------------------------------------------- */")
        self.w(0, '#include "pyrt.hpp"')
        self.w(0)
        wrapper_marker = len(self.buf)   # filled in once all wrappers are known

        if mod.classes:
            self.w(0, "/* class instances: generated C++ objects */")
            for c in mod.classes:
                self.w(0, f"typedef struct {c.name} {c.name};")
            self.w(0)
            for c in mod.classes:
                self.emit_class_struct(c)
            self.w(0)
            for c in mod.classes:
                self.w(0, self.ctor_signature(c) + ";")
                for m in c.methods:
                    self.w(0, self.method_signature(c, m) + ";")
            self.w(0)

        if mod.funcs:
            self.w(0, "/* forward declarations (PySub allows mutual recursion) */")
            for f in mod.funcs:
                self.w(0, self.signature(f) + ";")
            self.w(0)

        for c in mod.classes:
            self.emit_class_ctor(c)
            self.w(0)
            for m in c.methods:
                self.emit_func(m, owner=c.name)
                self.w(0)

        for f in mod.funcs:
            self.emit_func(f)
            self.w(0)
        self.emit_main(mod)
        if self.wrappers:
            wlines = ["/* print-adapter wrappers for nested/class containers */"]
            for _, body in self.wrappers.values():
                wlines.append(body)
            wlines.append("")
            self.buf[wrapper_marker:wrapper_marker] = wlines
        return "\n".join(self.buf) + "\n"

    # ---- classes -------------------------------------------------------
    @staticmethod
    def method_name(cls: str, m: str) -> str:
        return f"m_{cls}_{m}"

    def emit_class_struct(self, c: A.ClassDef) -> None:
        info = self.tc.classes[c.name]
        self.w(0, f"struct {c.name} {{")
        for name, t in zip(info.field_names, info.fields):
            self.w(1, f"{ctype(t)}{name};")
        self.w(0, "};")

    def ctor_signature(self, c: A.ClassDef) -> str:
        info = self.tc.classes[c.name]
        if info.init is None:
            return f"static std::shared_ptr<{c.name}> {c.name}_new(void)"
        ps = ", ".join(f"{ctype(t)}p_{p.name}" for p, t in
                       zip(info.init.node.params[1:], info.init.params))
        return f"static std::shared_ptr<{c.name}> {c.name}_new({ps or 'void'})"

    def emit_class_ctor(self, c: A.ClassDef) -> None:
        info = self.tc.classes[c.name]
        self.w(0, self.ctor_signature(c) + " {")
        self.w(1, f"auto p_self = std::make_shared<{c.name}>();")
        for name, t in zip(info.field_names, info.fields):
            self.w(1, f"p_self->{name} = {zero(t)};")
        if info.init is not None:
            args = ", ".join(f"p_{p.name}" for p in info.init.node.params[1:])
            call_args = "p_self" + (f", {args}" if args else "")
            self.w(1, f"{self.method_name(c.name, '__init__')}({call_args});")
        self.w(1, "return p_self;")
        self.w(0, "}")

    def method_signature(self, c: A.ClassDef, m: A.FuncDef) -> str:
        sig = self.tc.classes[c.name].methods[m.name]
        ps = ", ".join(f"{ctype(t)}p_{p.name}" for p, t in
                       zip(m.params[1:], sig.params))
        ps = f"std::shared_ptr<{c.name}> p_self" + (", " + ps if ps else "")
        return f"static {ctype(sig.ret)}{self.method_name(c.name, m.name)}({ps})"

    def signature(self, f: A.FuncDef) -> str:
        sig = self.tc.funcs[f.name]
        ps = ", ".join(f"{ctype(t)}p_{p.name}" for p, t in zip(f.params, sig.params))
        return f"static {ctype(sig.ret)}f_{f.name}({ps or 'void'})"

    def emit_func(self, f: A.FuncDef, owner: Optional[str] = None) -> None:
        if owner is not None:
            self.w(0, self.method_signature(self.tc.classes[owner].node, f) + " {")
            sig = self.tc.classes[owner].methods[f.name]
            locals_ = {k: v for k, v in f.locals_.items() if k != "self"}
        else:
            self.w(0, self.signature(f) + " {")
            sig = self.tc.funcs[f.name]
            locals_ = f.locals_
        for name, t in locals_.items():
            if t is ERR:
                continue
            self.w(1, f"{ctype(t)}p_{name} = {zero(t)};")
        if locals_:
            self.w(0)
        for s in f.body:
            self.stmt(s, 1)
        if sig.ret != NONE:
            self.w(1, f"return {zero(sig.ret)};   /* unreachable: checked by PYTHIA */")
        self.w(0, "}")

    def emit_main(self, mod: A.Module) -> None:
        self.w(0, "int main(void) {")
        self.w(1, "try {")
        for name, t in mod.globals_.items():
            if t is ERR:
                continue
            self.w(2, f"{ctype(t)}p_{name} = {zero(t)};")
        if mod.globals_:
            self.w(0)
        for s in mod.main:
            self.stmt(s, 2)
        self.w(2, "return 0;")
        self.w(1, "} catch (const PythonException &exc) {")
        self.w(2, "py_print_exception(exc);")
        self.w(2, "return 1;")
        self.w(1, "}")
        self.w(0, "}")

    # ---- statements --------------------------------------------------------
    # ---- container access helpers ------------------------------------------
    def dict_set(self, base_c: str, base_ty: Ty, key_c: str, val_c: str) -> str:
        rt = dict_rt_name(base_ty)
        return f"{rt}_set({base_c}, {key_c}, {val_c});"

    def stmt(self, s: A.Node, d: int) -> None:
        if isinstance(s, A.Assign):
            if isinstance(s.target, A.Subscript):
                base = s.target.value
                bt = base.ty
                if bt.name == "dict":
                    self.w(d, self.dict_set(self.ex(base), bt,
                                            self.ex(s.target.index), self.ex(s.value)))
                else:
                    rt = list_rt_name(bt)
                    vexpr = self.ex(s.value)
                    if rt == "PyListList":
                        vexpr = f"(void *)({vexpr})"
                    self.w(d, f"{rt}_set({self.ex(base)}, {self.ex(s.target.index)}, "
                              f"{vexpr});")
            elif isinstance(s.target, A.Attribute):
                self.w(d, f"{self.ex(s.target.value)}->{s.target.attr} = "
                          f"{self.ex(s.value)};")
            else:
                self.w(d, f"p_{s.target.id} = {self.ex(s.value)};")

        elif isinstance(s, A.AugAssign):
            fake = A.BinOp(s.line, s.col, op=s.op, left=s.target, right=s.value)
            fake.ty = s.target.ty
            if isinstance(s.target, A.Subscript):
                base = s.target.value
                bt = base.ty
                if bt.name == "dict":
                    self.w(d, self.dict_set(self.ex(base), bt,
                                            self.ex(s.target.index), self.binop(fake)))
                else:
                    rt = list_rt_name(bt)
                    vexpr = self.binop(fake)
                    if rt == "PyListList":
                        vexpr = f"(void *)({vexpr})"
                    self.w(d, f"{rt}_set({self.ex(base)}, {self.ex(s.target.index)}, "
                              f"{vexpr});")
            elif isinstance(s.target, A.Attribute):
                self.w(d, f"{self.ex(s.target.value)}->{s.target.attr} = "
                          f"{self.binop(fake)};")
            else:
                self.w(d, f"p_{s.target.id} = {self.binop(fake)};")

        elif isinstance(s, A.ExprStmt):
            v = s.value
            if isinstance(v, A.Call) and v.func == "print":
                self.emit_print(v, d)
            else:
                self.w(d, f"(void)({self.ex(v)});")

        elif isinstance(s, A.Return):
            if s.value is None:
                self.w(d, "return;")
            else:
                self.w(d, f"return {self.ex(s.value)};")

        elif isinstance(s, A.If):
            self.w(d, f"if ({self.cond(s.test)}) {{")
            for x in s.body:
                self.stmt(x, d + 1)
            if s.orelse:
                self.w(d, "} else {")
                for x in s.orelse:
                    self.stmt(x, d + 1)
            self.w(d, "}")

        elif isinstance(s, A.While):
            self.w(d, f"while ({self.cond(s.test)}) {{")
            for x in s.body:
                self.stmt(x, d + 1)
            self.w(d, "}")

        elif isinstance(s, A.ForRange):
            stop, step, ctr = self.fresh(), self.fresh(), self.fresh()
            self.w(d, "{")
            self.w(d + 1, f"int64_t {stop} = {self.ex(s.stop)};")
            self.w(d + 1, f"int64_t {step} = "
                          f"{self.ex(s.step) if s.step is not None else '1'};")
            self.w(d + 1, f'if ({step} == 0) py_raise("ValueError", '
                          f'"range() arg 3 must not be zero");')
            # Python precomputes the range sequence: the loop runs a fixed
            # number of times and rebinds the loop variable from that
            # sequence each pass, regardless of what the body does to it.
            # A C for-loop that reuses p_<var> as its own induction variable
            # would let a body reassignment corrupt the iteration count (up
            # to an infinite loop) -- so the *hidden* counter drives the
            # loop, and p_<var> is just assigned from it each iteration.
            self.w(d + 1, f"for (int64_t {ctr} = {self.ex(s.start)};")
            self.w(d + 1, f"     {step} > 0 ? {ctr} < {stop} : {ctr} > {stop};")
            self.w(d + 1, f"     {ctr} += {step}) {{")
            self.w(d + 2, f"p_{s.var} = {ctr};")
            for x in s.body:
                self.stmt(x, d + 2)
            self.w(d + 1, "}")
            self.w(d, "}")

        elif isinstance(s, A.ForEach):
            it, idx = self.fresh(), self.fresh()
            t = s.iter.ty
            self.w(d, "{")
            if t.name == "list":
                rt = list_rt_name(t)
                self.w(d + 1, f"{rt} *{it} = {self.ex(s.iter)};")
                self.w(d + 1, f"for (int64_t {idx} = 0; {idx} < static_cast<int64_t>({it}->data.size()); {idx}++) {{")
                if rt == "PyListList":
                    self.w(d + 2, f"p_{s.var} = ({ctype(t.elem)}){it}->data[{idx}];")
                else:
                    self.w(d + 2, f"p_{s.var} = {it}->data[{idx}];")
            elif t.name == "dict":
                rt = dict_rt_name(t)
                self.w(d + 1, f"{rt} *{it} = {self.ex(s.iter)};")
                self.w(d + 1, f"for (int64_t {idx} = 0; {idx} < {it}->size(); {idx}++) {{")
                self.w(d + 2, f"p_{s.var} = {it}->keys[{idx}];")
            else:
                self.w(d + 1, f"PyStr *{it} = {self.ex(s.iter)};")
                self.w(d + 1, f"for (int64_t {idx} = 0; {idx} < static_cast<int64_t>({it}->data.size()); {idx}++) {{")
                self.w(d + 2, f"p_{s.var} = pystr_new({it}->data.data() + {idx}, 1);")
            for x in s.body:
                self.stmt(x, d + 2)
            self.w(d + 1, "}")
            self.w(d, "}")

        elif isinstance(s, A.Break):
            self.w(d, "break;")
        elif isinstance(s, A.Continue):
            self.w(d, "continue;")
        elif isinstance(s, A.Pass):
            self.w(d, ";")

        elif isinstance(s, A.TryExcept):
            self.w(d, "{")
            self.w(d + 1, "try {")
            for x in s.body:
                self.stmt(x, d + 2)
            self.w(d + 1, "} catch (const PythonException &exc) {")
            named = [hd for hd in s.handlers if hd.exc_name is not None]
            bare = [hd for hd in s.handlers if hd.exc_name is None]
            for i, hd in enumerate(named):
                kw = "if" if i == 0 else "} else if"
                self.w(d + 2, f'{kw} (exc.name() == "{hd.exc_name}") {{')
                if hd.bind:
                    self.w(d + 3, f"PyStr *p_{hd.bind} = pystr_lit(exc.message().c_str());")
                for x in hd.body:
                    self.stmt(x, d + 3)
            if named:
                if bare:
                    self.w(d + 2, "} else {")
                    if bare[0].bind:
                        self.w(d + 3, f"PyStr *p_{bare[0].bind} = pystr_lit(exc.message().c_str());")
                    for x in bare[0].body:
                        self.stmt(x, d + 3)
                    self.w(d + 2, "}")
                else:
                    self.w(d + 2, "} else {")
                    self.w(d + 3, "throw;")
                    self.w(d + 2, "}")
            elif bare:
                if bare[0].bind:
                    self.w(d + 2, f"PyStr *p_{bare[0].bind} = pystr_lit(exc.message().c_str());")
                for x in bare[0].body:
                    self.stmt(x, d + 2)
            self.w(d + 1, "}")
            self.w(d, "}")

        elif isinstance(s, A.Raise):
            msg = self.ex(s.message) if s.message is not None else 'pystr_lit("")'
            self.w(d, f'py_raise_pystr("{s.exc_name}", {msg});')

    def emit_print(self, call: A.Call, d: int) -> None:
        self.w(d, "py_print_begin();")
        for a in call.args:
            self.w(d, "py_print_sep();")
            self.w(d, self.print_call(a) + ";")
        if not call.args:
            pass
        self.w(d, "py_print_end();")

    def print_call(self, a: A.Node) -> str:
        t, e = a.ty, self.ex(a)
        if t == INT:
            return f"py_print_i64({e})"
        if t == FLOAT:
            return f"py_print_f64({e})"
        if t == BOOL:
            return f"py_print_bool({e})"
        if t == STR:
            return f"py_print_str({e})"
        if t.name == "list":
            rt = list_rt_name(t)
            if rt != "PyListList":
                suffix = {"int": "i64", "float": "f64", "bool": "bool", "str": "str"}[t.elem.name]
                return f"py_print_list_{suffix}({e})"
            wrapper = self.print_wrapper_for(t.elem)
            return f"py_print_list_generic({e}, {wrapper})"
        if t.name == "dict":
            suffix = {"int": "int", "str": "str"}[t.key.name] + \
                     {"int": "int", "float": "float", "bool": "bool", "str": "str"}[t.elem.name]
            return f"py_print_dict_{suffix}({e})"
        return f"(void)({e})"

    def print_wrapper_for(self, elem_ty: Ty) -> str:
        """A single-level list[T] prints via py_print_list_<T> directly; a
        nested/class list stores void* and needs an adapter matching
        py_print_list_generic's void(*)(void*) callback signature. Wrappers
        are collected as they're discovered and spliced in after the
        #include, so forward reference is never an issue."""
        key = str(elem_ty)
        if key in self.wrappers:
            return self.wrappers[key][0]
        name = f"pw_{len(self.wrappers) + 1}"
        rt = list_rt_name(elem_ty) if elem_ty.name == "list" else None
        if elem_ty.name == "list" and rt != "PyListList":
            suffix = {"int": "i64", "float": "f64", "bool": "bool", "str": "str"}[elem_ty.elem.name]
            body = (f"static void {name}(void *p) {{ "
                    f"py_print_list_{suffix}(({rt} *)p); }}")
        else:
            # Reached only if the type checker ever allows printing a list
            # of class instances or triple-nested lists; both are refused
            # at the type-check stage today (no reproducible repr / depth
            # cap), so this path exists for forward compatibility only.
            body = f"static void {name}(void *p) {{ (void)p; }}"
        self.wrappers[key] = (name, body)
        return name

    # ---- conditions --------------------------------------------------------
    def cond(self, e: A.Node) -> str:
        """Boolean context: short-circuit maps straight onto C's && / ||."""
        if isinstance(e, A.BoolOp):
            op = "&&" if e.op == "and" else "||"
            return "(" + f" {op} ".join(self.cond(v) for v in e.values) + ")"
        if isinstance(e, A.UnaryOp) and e.op == "not":
            return f"(!{self.cond(e.operand)})"
        if isinstance(e, A.Coerce):
            return self.cond(e.value)
        return self.truthy(self.ex(e), e.ty)

    @staticmethod
    def truthy(expr: str, t: Optional[Ty]) -> str:
        if t is None or t is ERR:
            return "false"
        if t == BOOL:
            return f"({expr})"
        if t == INT:
            return f"(({expr}) != 0)"
        if t == FLOAT:
            return f"(({expr}) != 0.0)"
        if t == STR:
            return f"pystr_truthy({expr})"
        if t.name in ("list", "dict"):
            return f"(({expr})->size() != 0)"
        return "true"          # class instances: always truthy (no __bool__/__len__ in PySub)

    # ---- expressions -------------------------------------------------------
    def ex(self, e: Optional[A.Node]) -> str:
        if e is None:
            return "0"
        if isinstance(e, A.IntLit):
            if e.value == -(2 ** 63):
                return "INT64_MIN"
            return f"INT64_C({e.value})"
        if isinstance(e, A.FloatLit):
            return repr(float(e.value))
        if isinstance(e, A.BoolLit):
            return "true" if e.value else "false"
        if isinstance(e, A.StrLit):
            return f"pystr_lit({c_string(e.value)})"
        if isinstance(e, A.NoneLit):
            return "0"
        if isinstance(e, A.Name):
            return f"p_{e.id}"

        if isinstance(e, A.Coerce):
            inner = self.ex(e.value)
            if e.to == FLOAT:
                return f"((double)({inner}))"
            if e.to == INT:
                return f"((int64_t)({inner}))"
            if e.to == BOOL:
                return self.truthy(inner, e.value.ty)
            return inner

        if isinstance(e, A.BinOp):
            return self.binop(e)

        if isinstance(e, A.Compare):
            l, r, lt = self.ex(e.left), self.ex(e.right), e.left.ty
            if e.op in ("in", "not in"):
                rt = e.right.ty
                if rt.name == "dict":
                    drt = dict_rt_name(rt)
                    test = f"{drt}_contains({r}, {l})"
                elif rt.name == "list":
                    lrt = list_rt_name(rt)
                    test = f"{lrt}_contains({r}, {l})"
                else:  # str in str
                    test = f"pystr_contains({r}, {l})"
                return test if e.op == "in" else f"(!{test})"
            if lt == STR:
                return f"(pystr_cmp({l}, {r}) {e.op} 0)"
            if lt.name == "list":
                rt = list_rt_name(lt)
                if rt == "PyListList":
                    return f"(({l}) {e.op} ({r}))"   # unreachable: only ==/!= allowed, and PyListList isn't compared today
                eq = f"{rt}_eq({l}, {r})"
                return eq if e.op == "==" else f"(!{eq})"
            return f"(({l}) {e.op} ({r}))"

        if isinstance(e, A.BoolOp):
            t = e.ty
            v = self.fresh()
            a, b = self.ex(e.values[0]), self.ex(e.values[1])
            test = self.truthy(v, t)
            body = f"{test} ? ({b}) : {v}" if e.op == "and" else f"{test} ? {v} : ({b})"
            return f"[&]() {{ {ctype(t)}{v} = ({a}); return {body}; }}()"

        if isinstance(e, A.UnaryOp):
            if e.op == "not":
                return f"(!{self.truthy(self.ex(e.operand), e.operand.ty)})"
            if e.op == "+":
                return self.ex(e.operand)
            if e.ty == INT:
                return f"py_neg_i64({self.ex(e.operand)})"
            return f"(-({self.ex(e.operand)}))"

        if isinstance(e, A.Subscript):
            bt = e.value.ty
            if bt == STR:
                return f"pystr_index({self.ex(e.value)}, {self.ex(e.index)})"
            if bt.name == "dict":
                rt = dict_rt_name(bt)
                return f"{rt}_get({self.ex(e.value)}, {self.ex(e.index)})"
            rt = list_rt_name(bt)
            if rt == "PyListList":
                return (f"({ctype(bt.elem)})PyListList_get({self.ex(e.value)}, "
                        f"{self.ex(e.index)})")
            return f"{rt}_get({self.ex(e.value)}, {self.ex(e.index)})"

        if isinstance(e, A.ListLit):
            rt = list_rt_name(e.ty)
            v = self.fresh()
            if rt == "PyListList":
                parts = [f"PyListList *{v} = PyListList_new();"]
                parts += [f"PyListList_append({v}, (void *)({self.ex(x)}));" for x in e.elts]
            else:
                parts = [f"{rt} *{v} = {rt}_new();"]
                parts += [f"{rt}_append({v}, {self.ex(x)});" for x in e.elts]
            return "[&]() { " + " ".join(parts) + f" return {v}; }}()"

        if isinstance(e, A.DictLit):
            rt = dict_rt_name(e.ty)
            v = self.fresh()
            parts = [f"{rt} *{v} = {rt}_new();"]
            parts += [f"{rt}_set({v}, {self.ex(k)}, {self.ex(val)});"
                     for k, val in zip(e.keys, e.values)]
            return "[&]() { " + " ".join(parts) + f" return {v}; }}()"

        if isinstance(e, A.Attribute):
            return f"{self.ex(e.value)}->{e.attr}"

        if isinstance(e, A.MethodCall):
            recv, rt_ = self.ex(e.recv), e.recv.ty
            if rt_.name == "list":
                rt = list_rt_name(rt_)
                if e.method == "append":
                    v = self.ex(e.args[0])
                    if rt == "PyListList":
                        v = f"(void *)({v})"
                    return f"({rt}_append({recv}, {v}), 0)"
                if e.method == "pop":
                    if rt == "PyListList":
                        return f"({ctype(rt_.elem)})PyListList_pop({recv})"
                    return f"{rt}_pop({recv})"
            if rt_.name == "dict":
                drt = dict_rt_name(rt_)
                if e.method == "get":
                    return (f"{drt}_get_default({recv}, {self.ex(e.args[0])}, "
                            f"{self.ex(e.args[1])})")
            if rt_ == STR:
                return f"pystr_{e.method}({recv})"
            if rt_.name in self.tc.classes:
                mname = self.method_name(rt_.name, e.method)
                args = ", ".join(self.ex(a) for a in e.args)
                return f"{mname}({recv}" + (f", {args})" if args else ")")
            return "0"

        if isinstance(e, A.Call):
            if e.func in self.tc.classes:
                args = ", ".join(self.ex(a) for a in e.args)
                return f"{e.func}_new({args})"
            return self.call(e)

        return "0"

    def binop(self, e: A.BinOp) -> str:
        op, t = e.op, e.ty
        l, r = self.ex(e.left), self.ex(e.right)
        lt = e.left.ty
        if op == "+" and t == STR:
            return f"pystr_concat({l}, {r})"
        if op == "+" and t.name == "list":
            rt = list_rt_name(t)
            if rt == "PyListList":
                return f"PyListList_concat({l}, {r})"
            return f"{rt}_concat({l}, {r})"
        if op == "*" and t == STR:
            return (f"pystr_repeat({l}, {r})" if lt == STR
                    else f"pystr_repeat({r}, {l})")
        if t == FLOAT or op == "/":
            fn = {"+": None, "-": None, "*": None,
                  "/": "py_truediv", "//": "py_floordiv_f64",
                  "%": "py_mod_f64", "**": "py_pow_f64"}.get(op)
            if fn:
                return f"{fn}({l}, {r})"
            return f"(({l}) {op} ({r}))"
        fn = {"+": "py_add_i64", "-": "py_sub_i64", "*": "py_mul_i64",
              "//": "py_floordiv_i64", "%": "py_mod_i64",
              "**": "py_pow_i64"}.get(op)
        if getattr(e, "no_guard", False) and op in ("+", "-", "*"):
            return f"(({l}) {op} ({r}))"    # proven safe by interval analysis
        return f"{fn}({l}, {r})" if fn else f"(({l}) {op} ({r}))"

    def call(self, e: A.Call) -> str:
        n = e.func
        if n == "len":
            a = e.args[0]
            return (f"pystr_len({self.ex(a)})" if a.ty == STR
                    else f"(({self.ex(a)})->size())")
        if n == "abs":
            a = e.args[0]
            return (f"py_abs_i64({self.ex(a)})" if e.ty == INT
                    else f"fabs({self.ex(a)})")
        if n in ("min", "max"):
            t = ctype(e.ty)
            x, y = self.fresh(), self.fresh()
            cmp = "<" if n == "min" else ">"
            return (f"[&]() {{ {t}{x} = ({self.ex(e.args[0])}); "
                    f"{t}{y} = ({self.ex(e.args[1])}); "
                    f"return {x} {cmp} {y} ? {x} : {y}; }}()")
        if n == "int":
            a = e.args[0]
            if a.ty == STR:
                return f"py_i64_from_str({self.ex(a)})"
            return f"((int64_t)({self.ex(a)}))"
        if n == "float":
            a = e.args[0]
            if a.ty == STR:
                return f"py_f64_from_str({self.ex(a)})"
            return f"((double)({self.ex(a)}))"
        if n == "str":
            a = e.args[0]
            m = {"int": "pystr_from_i64", "float": "pystr_from_f64",
                 "bool": "pystr_from_bool", "str": None}[a.ty.name]
            return self.ex(a) if m is None else f"{m}({self.ex(a)})"
        if n == "bool":
            a = e.args[0]
            return self.truthy(self.ex(a), a.ty)
        args = ", ".join(self.ex(a) for a in e.args)
        return f"f_{n}({args})"


def emit(mod: A.Module, tc: TypeChecker, src_name: str) -> str:
    return Emitter(tc).emit_module(mod, src_name)
